# @Author: Rafael Direito
# @Date:   09-05-2022 16:55:45
# @Last Modified by:   Rafael Direito
# @Last Modified time: 09-05-2022 17:27:28

name: GitHub Actions Deployment Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_website:
    runs-on: self-hosted
    steps:
      - run: | # get inside the project and deal with the dependencies
          cd ${{ github.workspace }}/project-documentation 
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - run: |
          cd ${{ github.workspace }}/project-documentation 
          npm run build
